### ISSUE TITLE
please teach me

### ISSUE THREAD

**Issue by InfernalAzazel** [yandricr/gpti-js#9]
1. Are the gpt api and DALL-E called by the author's server free, or do they cost money?
2. What is the hardware configuration of the author's server?
3. If you use free api, please tell me the address, especially dall-e, I have been looking for free api interface

**Comment by yandricr** [comment]
I have conducted a thorough search for free APIs for GPT, DALL-E, and other models, directly calling them from the original server. So far, I haven't found any free options available, as most of these tools typically come with associated costs.

Regarding the original server's hardware configuration, information about this specific aspect may not be available.

Since I couldn't find a free API interface for DALL-E and other models, I chose to understand and decode the codes of some existing applications to make these models work without associated costs. My API does not involve any expenses; all the services it provides are entirely free. I have applied this approach by deciphering the codes of my API and configuring my server to ensure error-free operation, thus guaranteeing efficient and hassle-free functionality for users. Furthermore, I have carried out this decryption process independently, as I have been unable to identify any original author

**Comment by yandricr** [comment]
Despite other services potentially having usage costs, my API is free for everyone. To generate income and maintain my server, I have integrated advertisements into the platform. This approach allows me to provide a service at no cost to users while still having the ability to cover operational expenses through advertising

**Comment by InfernalAzazel** [comment]
> I have conducted a thorough search for free APIs for GPT, DALL-E, and other models, directly calling them from the original server. So far, I haven't found any free options available, as most of these tools typically come with associated costs.
> 
> Regarding the original server's hardware configuration, information about this specific aspect may not be available.
> 
> Since I couldn't find a free API interface for DALL-E and other models, I chose to understand and decode the codes of some existing applications to make these models work without associated costs. My API does not involve any expenses; all the services it provides are entirely free. I have applied this approach by deciphering the codes of my API and configuring my server to ensure error-free operation, thus guaranteeing efficient and hassle-free functionality for users. Furthermore, I have carried out this decryption process independently, as I have been unable to identify any original author

awesome you

**Comment by InfernalAzazel** [comment]
> Despite other services potentially having usage costs, my API is free for everyone. To generate income and maintain my server, I have integrated advertisements into the platform. This approach allows me to provide a service at no cost to users while still having the ability to cover operational expenses through advertising

It's very good. I feel that gpti will be popular. After all, it is one of the most comprehensive free models that can be found now. No.
